config/routes.rb
Rails.application.routes.draw do
  resources :records
  resources :tables
  resources :mods
  root 'mods#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mod.rb
class Mod < ApplicationRecord
end

app/models/record.rb
class Record < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
  def columns
  	JSON.parse(fields)
  end
end

app/models/table_mod.rb
class TableMod < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mods_controller.rb
class ModsController < ApplicationController
  before_action :set_mod, only: [:show, :edit, :update, :destroy]

  # GET /mods
  # GET /mods.json
  def index
    @mods = Mod.all
  end

  # GET /mods/1
  # GET /mods/1.json
  def show
  end

  # GET /mods/new
  def new
    @mod = Mod.new
  end

  # GET /mods/1/edit
  def edit
  end

  # POST /mods
  # POST /mods.json
  def create
    @mod = Mod.new(mod_params)

    respond_to do |format|
      if @mod.save
        format.html { redirect_to @mod, notice: 'Mod was successfully created.' }
        format.json { render :show, status: :created, location: @mod }
      else
        format.html { render :new }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mods/1
  # PATCH/PUT /mods/1.json
  def update
    respond_to do |format|
      if @mod.update(mod_params)
        format.html { redirect_to @mod, notice: 'Mod was successfully updated.' }
        format.json { render :show, status: :ok, location: @mod }
      else
        format.html { render :edit }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mods/1
  # DELETE /mods/1.json
  def destroy
    @mod.destroy
    respond_to do |format|
      format.html { redirect_to mods_url, notice: 'Mod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mod
      @mod = Mod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mod_params
      params.require(:mod).permit(:name, :title, :icon, :bgcolor, :table_id)
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def record_params
      params.require(:record).permit(:table_id, :values, :user_id)
    end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url, notice: 'Table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.require(:table).permit(:title, :fields)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/tables_helper.rb
module TablesHelper

  def types
  	['integer', 'varchar', 'float','datetime']
  end

  def selected(type, value)
  	if type == value
  	  'selected'	
  	end
  end

  def checked?(value)
  	if value == "on"
  	  'checked'
  	end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ModularV1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mods/_form.html.erb
<%= form_with(model: mod, local: true) do |form| %>
  <% if mod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mod.errors.count, "error") %> prohibited this mod from being saved:</h2>

      <ul>
        <% mod.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon %>
  </div>

  <div class="field">
    <%= form.label :bgcolor %>
    <%= form.text_field :bgcolor %>
  </div>

  <div class="field">
    <%= form.label :table_id %>
    <%= form.text_field :table_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mods/edit.html.erb
<h1>Editing Mod</h1>

<%= render 'form', mod: @mod %>

<%= link_to 'Show', @mod %> |
<%= link_to 'Back', mods_path %>

app/views/mods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Icon</th>
      <th>Bgcolor</th>
      <th>Table</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mods.each do |mod| %>
      <tr>
        <td><%= mod.name %></td>
        <td><%= mod.title %></td>
        <td><%= mod.icon %></td>
        <td><%= mod.bgcolor %></td>
        <td><%= mod.table_id %></td>
        <td><%= link_to 'Show', mod %></td>
        <td><%= link_to 'Edit', edit_mod_path(mod) %></td>
        <td><%= link_to 'Destroy', mod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mod', new_mod_path %>

app/views/mods/new.html.erb
<h1>New Mod</h1>

<%= render 'form', mod: @mod %>

<%= link_to 'Back', mods_path %>

app/views/mods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mod.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @mod.title %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @mod.icon %>
</p>

<p>
  <strong>Bgcolor:</strong>
  <%= @mod.bgcolor %>
</p>

<p>
  <strong>Table:</strong>
  <%= @mod.table_id %>
</p>

<%= link_to 'Edit', edit_mod_path(@mod) %> |
<%= link_to 'Back', mods_path %>

app/views/records/_form.html.erb
<%= form_with(model: record, local: true) do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :table_id %>
    <%= form.number_field :table_id %>
  </div>

  <div class="field">
    <%= form.label :values %>
    <%= form.text_area :values %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Records</h1>

<table>
  <thead>
    <tr>
      <th>Table</th>
      <th>Values</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.table_id %></td>
        <td><%= record.values %></td>
        <td><%= record.user_id %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Table:</strong>
  <%= @record.table_id %>
</p>

<p>
  <strong>Values:</strong>
  <%= @record.values %>
</p>

<p>
  <strong>User:</strong>
  <%= @record.user_id %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

app/views/tables/_form.html.erb
<%= form_with(model: table, local: true, id: 'form_table') do |form| %>
  
  <% if table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
        <% table.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Nome" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label "Colunas da Tabela" %>
    <a href="#!" class="add-field">Add campo</a>
    <table class="table" id="fields" width="100%">
      <thead>
        <tr>
          <th>Título</th>
          <th>Nome</th>
          <th>Tipo de Campo</th>
          <th>Nulo?</th>
        </tr>
      </thead>
      <tbody>
        <% @table.columns.each do  |column| %>
          <tr class="trField">
            <td class="tdTitle"><input type="text" name="fieldTitle" value="<%= column["title"] %>" required></td>
            <td class="tdName"><input type="text" name="fieldName" value="<%= column["name"] %>" required></td>
            <td class="tdType">
              <select name="fieldType">
                <% types.each do |type| %>  
                  <option <%= selected(type, column["type"]) %> value="<%= type %>"><%= type %></option>
                <% end %>
              </select>
            </td>
            <td class="tdNullable"><input type="checkbox" <%= checked?(column["notnull"]) %> name="fieldNull"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= form.hidden_field :fields %>
  </div>

  <div class="actions">
      <%= form.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tables</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.title %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New Table</h1>

<%= render 'form', table: @table %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @table.title %>
</p>

<p>
  <strong>Fields:</strong>
  <%= @table.fields %>
</p>

<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>